project:
  type: website
  resources:
    - cv.pdf

website:
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: methods.qmd
        text: Statistical Methods
      - href: team.qmd
        text: Team



  page-footer:
    right: "Â© 2025 Keivan Bolouri"
    

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual



